# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'thesisgui.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_thermalCalc(object):
    def setupUi(self, thermalCalc):
        thermalCalc.setObjectName("thermalCalc")
        thermalCalc.resize(395, 590)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(thermalCalc.sizePolicy().hasHeightForWidth())
        thermalCalc.setSizePolicy(sizePolicy)
        thermalCalc.setMinimumSize(QtCore.QSize(395, 590))
        thermalCalc.setMaximumSize(QtCore.QSize(395, 590))
        thermalCalc.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly)
        self.centralwidget = QtWidgets.QWidget(thermalCalc)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 391, 541))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.groupBox = QtWidgets.QGroupBox(self.page)
        self.groupBox.setGeometry(QtCore.QRect(10, 20, 371, 481))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.LaTS = QtWidgets.QGroupBox(self.groupBox)
        self.LaTS.setGeometry(QtCore.QRect(10, 30, 351, 131))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.LaTS.setFont(font)
        self.LaTS.setObjectName("LaTS")
        self.gridLayout = QtWidgets.QGridLayout(self.LaTS)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.altitude = QtWidgets.QLabel(self.LaTS)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.altitude.setFont(font)
        self.altitude.setObjectName("altitude")
        self.horizontalLayout_3.addWidget(self.altitude)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.altitudeBox = QtWidgets.QDoubleSpinBox(self.LaTS)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(False)
        self.altitudeBox.setFont(font)
        self.altitudeBox.setMaximum(1000000.0)
        self.altitudeBox.setObjectName("altitudeBox")
        self.horizontalLayout_3.addWidget(self.altitudeBox)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.longitude = QtWidgets.QLabel(self.LaTS)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.longitude.setFont(font)
        self.longitude.setObjectName("longitude")
        self.horizontalLayout_2.addWidget(self.longitude)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.longitudeBox = QtWidgets.QDoubleSpinBox(self.LaTS)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.longitudeBox.setFont(font)
        self.longitudeBox.setDecimals(4)
        self.longitudeBox.setMinimum(-180.0)
        self.longitudeBox.setMaximum(180.0)
        self.longitudeBox.setProperty("value", 121.0437)
        self.longitudeBox.setObjectName("longitudeBox")
        self.horizontalLayout_2.addWidget(self.longitudeBox)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.latitude = QtWidgets.QLabel(self.LaTS)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.latitude.setFont(font)
        self.latitude.setObjectName("latitude")
        self.horizontalLayout.addWidget(self.latitude)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.latitudeBox = QtWidgets.QDoubleSpinBox(self.LaTS)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.latitudeBox.setFont(font)
        self.latitudeBox.setDecimals(4)
        self.latitudeBox.setMinimum(-90.0)
        self.latitudeBox.setMaximum(90.0)
        self.latitudeBox.setProperty("value", 14.676)
        self.latitudeBox.setObjectName("latitudeBox")
        self.horizontalLayout.addWidget(self.latitudeBox)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.LaTS_2 = QtWidgets.QGroupBox(self.groupBox)
        self.LaTS_2.setGeometry(QtCore.QRect(10, 160, 351, 71))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.LaTS_2.setFont(font)
        self.LaTS_2.setObjectName("LaTS_2")
        self.layoutWidget = QtWidgets.QWidget(self.LaTS_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 331, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.dateEdit = QtWidgets.QDateEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.dateEdit.setFont(font)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_4.addWidget(self.dateEdit)
        self.LaTS_3 = QtWidgets.QGroupBox(self.groupBox)
        self.LaTS_3.setGeometry(QtCore.QRect(10, 230, 351, 131))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.LaTS_3.setFont(font)
        self.LaTS_3.setObjectName("LaTS_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.LaTS_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.altitude_2 = QtWidgets.QLabel(self.LaTS_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.altitude_2.setFont(font)
        self.altitude_2.setObjectName("altitude_2")
        self.horizontalLayout_19.addWidget(self.altitude_2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem4)
        self.lwEmissBox = QtWidgets.QDoubleSpinBox(self.LaTS_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(False)
        self.lwEmissBox.setFont(font)
        self.lwEmissBox.setMaximum(1.0)
        self.lwEmissBox.setObjectName("lwEmissBox")
        self.horizontalLayout_19.addWidget(self.lwEmissBox)
        self.gridLayout_2.addLayout(self.horizontalLayout_19, 2, 0, 1, 1)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.longitude_2 = QtWidgets.QLabel(self.LaTS_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.longitude_2.setFont(font)
        self.longitude_2.setObjectName("longitude_2")
        self.horizontalLayout_20.addWidget(self.longitude_2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem5)
        self.lwReflBox = QtWidgets.QDoubleSpinBox(self.LaTS_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lwReflBox.setFont(font)
        self.lwReflBox.setDecimals(4)
        self.lwReflBox.setMinimum(0.0)
        self.lwReflBox.setMaximum(1.0)
        self.lwReflBox.setProperty("value", 1.0)
        self.lwReflBox.setObjectName("lwReflBox")
        self.horizontalLayout_20.addWidget(self.lwReflBox)
        self.gridLayout_2.addLayout(self.horizontalLayout_20, 1, 0, 1, 1)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.latitude_2 = QtWidgets.QLabel(self.LaTS_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.latitude_2.setFont(font)
        self.latitude_2.setObjectName("latitude_2")
        self.horizontalLayout_21.addWidget(self.latitude_2)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem6)
        self.swReflBox = QtWidgets.QDoubleSpinBox(self.LaTS_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.swReflBox.setFont(font)
        self.swReflBox.setDecimals(4)
        self.swReflBox.setMinimum(0.0)
        self.swReflBox.setMaximum(1.0)
        self.swReflBox.setProperty("value", 1.0)
        self.swReflBox.setObjectName("swReflBox")
        self.horizontalLayout_21.addWidget(self.swReflBox)
        self.gridLayout_2.addLayout(self.horizontalLayout_21, 0, 0, 1, 1)
        self.oneNext = QtWidgets.QCommandLinkButton(self.page)
        self.oneNext.setGeometry(QtCore.QRect(310, 500, 71, 41))
        self.oneNext.setObjectName("oneNext")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.BP = QtWidgets.QGroupBox(self.page_2)
        self.BP.setGeometry(QtCore.QRect(10, 20, 371, 481))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.BP.setFont(font)
        self.BP.setObjectName("BP")
        self.TP = QtWidgets.QGroupBox(self.BP)
        self.TP.setGeometry(QtCore.QRect(10, 30, 351, 190))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.TP.setFont(font)
        self.TP.setObjectName("TP")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.TP)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.thickness = QtWidgets.QLabel(self.TP)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.thickness.setFont(font)
        self.thickness.setObjectName("thickness")
        self.horizontalLayout_5.addWidget(self.thickness)
        spacerItem7 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem7)
        self.thicknessBox = QtWidgets.QDoubleSpinBox(self.TP)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.thicknessBox.setFont(font)
        self.thicknessBox.setDecimals(4)
        self.thicknessBox.setMaximum(10.0)
        self.thicknessBox.setSingleStep(0.5)
        self.thicknessBox.setProperty("value", 0.1)
        self.thicknessBox.setObjectName("thicknessBox")
        self.horizontalLayout_5.addWidget(self.thicknessBox)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.spec_heat = QtWidgets.QLabel(self.TP)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.spec_heat.setFont(font)
        self.spec_heat.setObjectName("spec_heat")
        self.horizontalLayout_6.addWidget(self.spec_heat)
        spacerItem8 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.spec_heatBox = QtWidgets.QDoubleSpinBox(self.TP)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.spec_heatBox.setFont(font)
        self.spec_heatBox.setDecimals(4)
        self.spec_heatBox.setMaximum(1000000.0)
        self.spec_heatBox.setProperty("value", 1000.0)
        self.spec_heatBox.setObjectName("spec_heatBox")
        self.horizontalLayout_6.addWidget(self.spec_heatBox)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.thermal_con = QtWidgets.QLabel(self.TP)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.thermal_con.setFont(font)
        self.thermal_con.setObjectName("thermal_con")
        self.horizontalLayout_7.addWidget(self.thermal_con)
        spacerItem9 = QtWidgets.QSpacerItem(1, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem9)
        self.thermal_conBox = QtWidgets.QDoubleSpinBox(self.TP)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.thermal_conBox.setFont(font)
        self.thermal_conBox.setDecimals(4)
        self.thermal_conBox.setMaximum(10000.0)
        self.thermal_conBox.setProperty("value", 1.13)
        self.thermal_conBox.setObjectName("thermal_conBox")
        self.horizontalLayout_7.addWidget(self.thermal_conBox)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.conv_coeff = QtWidgets.QLabel(self.TP)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.conv_coeff.setFont(font)
        self.conv_coeff.setObjectName("conv_coeff")
        self.horizontalLayout_8.addWidget(self.conv_coeff)
        spacerItem10 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem10)
        self.conv_coeffBox = QtWidgets.QDoubleSpinBox(self.TP)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.conv_coeffBox.setFont(font)
        self.conv_coeffBox.setDecimals(4)
        self.conv_coeffBox.setProperty("value", 4.5)
        self.conv_coeffBox.setObjectName("conv_coeffBox")
        self.horizontalLayout_8.addWidget(self.conv_coeffBox)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.density = QtWidgets.QLabel(self.TP)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.density.setFont(font)
        self.density.setObjectName("density")
        self.horizontalLayout_9.addWidget(self.density)
        spacerItem11 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem11)
        self.densityBox = QtWidgets.QDoubleSpinBox(self.TP)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.densityBox.setFont(font)
        self.densityBox.setDecimals(4)
        self.densityBox.setMaximum(100000.0)
        self.densityBox.setProperty("value", 2400.0)
        self.densityBox.setObjectName("densityBox")
        self.horizontalLayout_9.addWidget(self.densityBox)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.RC = QtWidgets.QGroupBox(self.BP)
        self.RC.setGeometry(QtCore.QRect(10, 220, 351, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.RC.setFont(font)
        self.RC.setObjectName("RC")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.RC)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.short_abs = QtWidgets.QLabel(self.RC)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.short_abs.setFont(font)
        self.short_abs.setObjectName("short_abs")
        self.horizontalLayout_10.addWidget(self.short_abs)
        spacerItem12 = QtWidgets.QSpacerItem(22, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem12)
        self.short_absBox = QtWidgets.QDoubleSpinBox(self.RC)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.short_absBox.setFont(font)
        self.short_absBox.setDecimals(4)
        self.short_absBox.setMaximum(1.0)
        self.short_absBox.setSingleStep(0.1)
        self.short_absBox.setProperty("value", 0.36)
        self.short_absBox.setObjectName("short_absBox")
        self.horizontalLayout_10.addWidget(self.short_absBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.long_emiss = QtWidgets.QLabel(self.RC)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.long_emiss.setFont(font)
        self.long_emiss.setObjectName("long_emiss")
        self.horizontalLayout_11.addWidget(self.long_emiss)
        spacerItem13 = QtWidgets.QSpacerItem(22, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem13)
        self.long_emissBox = QtWidgets.QDoubleSpinBox(self.RC)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.long_emissBox.setFont(font)
        self.long_emissBox.setDecimals(4)
        self.long_emissBox.setMaximum(1.0)
        self.long_emissBox.setSingleStep(0.1)
        self.long_emissBox.setProperty("value", 0.95)
        self.long_emissBox.setObjectName("long_emissBox")
        self.horizontalLayout_11.addWidget(self.long_emissBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.twoBack = QtWidgets.QCommandLinkButton(self.page_2)
        self.twoBack.setGeometry(QtCore.QRect(10, 500, 71, 41))
        icon = QtGui.QIcon.fromTheme("back")
        self.twoBack.setIcon(icon)
        self.twoBack.setObjectName("twoBack")
        self.save = QtWidgets.QCommandLinkButton(self.page_2)
        self.save.setGeometry(QtCore.QRect(310, 500, 71, 41))
        icon = QtGui.QIcon.fromTheme("down")
        self.save.setIcon(icon)
        self.save.setObjectName("save")
        self.stackedWidget.addWidget(self.page_2)
        thermalCalc.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(thermalCalc)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 395, 19))
        self.menubar.setObjectName("menubar")
        self.Home = QtWidgets.QMenu(self.menubar)
        self.Home.setObjectName("Home")
        self.About = QtWidgets.QMenu(self.menubar)
        self.About.setObjectName("About")
        thermalCalc.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(thermalCalc)
        self.statusbar.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.statusbar.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.statusbar.setObjectName("statusbar")
        thermalCalc.setStatusBar(self.statusbar)
        self.menubar.addAction(self.Home.menuAction())
        self.menubar.addAction(self.About.menuAction())

        self.retranslateUi(thermalCalc)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(thermalCalc)
        thermalCalc.setTabOrder(self.latitudeBox, self.longitudeBox)
        thermalCalc.setTabOrder(self.longitudeBox, self.altitudeBox)
        thermalCalc.setTabOrder(self.altitudeBox, self.dateEdit)
        thermalCalc.setTabOrder(self.dateEdit, self.swReflBox)
        thermalCalc.setTabOrder(self.swReflBox, self.lwReflBox)
        thermalCalc.setTabOrder(self.lwReflBox, self.lwEmissBox)
        thermalCalc.setTabOrder(self.lwEmissBox, self.oneNext)
        thermalCalc.setTabOrder(self.oneNext, self.thicknessBox)
        thermalCalc.setTabOrder(self.thicknessBox, self.spec_heatBox)
        thermalCalc.setTabOrder(self.spec_heatBox, self.thermal_conBox)
        thermalCalc.setTabOrder(self.thermal_conBox, self.conv_coeffBox)
        thermalCalc.setTabOrder(self.conv_coeffBox, self.densityBox)
        thermalCalc.setTabOrder(self.densityBox, self.short_absBox)
        thermalCalc.setTabOrder(self.short_absBox, self.long_emissBox)
        thermalCalc.setTabOrder(self.long_emissBox, self.twoBack)
        thermalCalc.setTabOrder(self.twoBack, self.save)

    def retranslateUi(self, thermalCalc):
        _translate = QtCore.QCoreApplication.translate
        thermalCalc.setWindowTitle(_translate("thermalCalc", "Thermal Load Calculator"))
        self.groupBox.setTitle(_translate("thermalCalc", "Settings"))
        self.LaTS.setTitle(_translate("thermalCalc", "Location Settings"))
        self.altitude.setText(_translate("thermalCalc", "<html><head/><body><p>altitude (<span style=\" font-style:italic;\">m</span>)</p></body></html>"))
        self.longitude.setText(_translate("thermalCalc", "<html><head/><body><p>longitude (<span style=\" vertical-align:super;\">o</span>)</p></body></html>"))
        self.latitude.setText(_translate("thermalCalc", "<html><head/><body><p>latitude (<span style=\" vertical-align:super;\">o</span>)</p></body></html>"))
        self.LaTS_2.setTitle(_translate("thermalCalc", "Date Settings"))
        self.label.setText(_translate("thermalCalc", "date (dd/mm/yyy)"))
        self.LaTS_3.setTitle(_translate("thermalCalc", "Environmental Settings"))
        self.altitude_2.setText(_translate("thermalCalc", "<html><head/><body><p>LW emissivity</p></body></html>"))
        self.longitude_2.setText(_translate("thermalCalc", "<html><head/><body><p>LW reflection coeff</p></body></html>"))
        self.latitude_2.setText(_translate("thermalCalc", "<html><head/><body><p>SW reflection coeff</p></body></html>"))
        self.oneNext.setText(_translate("thermalCalc", "Next"))
        self.BP.setTitle(_translate("thermalCalc", "Wall Properties"))
        self.TP.setTitle(_translate("thermalCalc", "Thermal Properties"))
        self.thickness.setText(_translate("thermalCalc", "<html><head/><body><p>thickness (<span style=\" font-style:italic;\">m</span>)</p></body></html>"))
        self.spec_heat.setText(_translate("thermalCalc", "<html><head/><body><p>specific heat (<span style=\" font-style:italic;\">J/kg.K</span>)</p></body></html>"))
        self.thermal_con.setText(_translate("thermalCalc", "<html><head/><body><p>thermal conductivity (<span style=\" font-style:italic;\">W/m.K</span>)</p></body></html>"))
        self.conv_coeff.setText(_translate("thermalCalc", "<html><head/><body><p>convective coeff (<span style=\" font-style:italic;\">W/m.K</span>)</p></body></html>"))
        self.density.setText(_translate("thermalCalc", "<html><head/><body><p>density (<span style=\" font-style:italic;\">kg/m</span><span style=\" font-style:italic; vertical-align:super;\">3</span>)</p></body></html>"))
        self.RC.setTitle(_translate("thermalCalc", "Radiation Constants"))
        self.short_abs.setText(_translate("thermalCalc", "SW absorptivity"))
        self.long_emiss.setText(_translate("thermalCalc", "LW emissivity"))
        self.twoBack.setText(_translate("thermalCalc", "Back"))
        self.save.setText(_translate("thermalCalc", "Save"))
        self.Home.setTitle(_translate("thermalCalc", "Home"))
        self.About.setTitle(_translate("thermalCalc", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    thermalCalc = QtWidgets.QMainWindow()
    ui = Ui_thermalCalc()
    ui.setupUi(thermalCalc)
    thermalCalc.show()
    sys.exit(app.exec_())

